<!-- 
Title 
  A  SERIES  OF  STATISTICAL  CHARTS,  ILLUSTRA-
TING  THE  CONDITIONS  OF  THE  DESCENDANTS  OF  FOR-
MER  AFRICAN  SLAVES  NOW  RESIDENT  IN  THE  UNITED
STATES  OF  AMERICA.

Title french
 UNE  SÉRIE  DE  CARTES  ET    DIAGRAMMES  STATISTIQUES  MONTRANT  LA
CONDITION  PRÉSENTE  DES  DESCENDANTS  DES  ANCIENS  ESCLAVES  AFRI-
CAINS  ACTEULLMENT  ÉTABLIS  DANS  LES  ETATS  UNIS  D'AMÉRIQUE.

Subtitle
"PREPARED AND EXECUTED BY"
"NEGRO STUDENTS UNDER THE"
"DIRECTION OF"
"ATLANTA UNIVERSITY"
"ATLANTA, GA."
"UNITED STATES OF AMERICA"

Subtitle french
"PREPARE ET EXECUTE PAR"
"NÈGRES ÉTUDIANTS SOUS"
"LA DIRECTION DE L’UNIVERSITÉ ATLANTA"
"D'ATLANTA"
"ETAT DE GEORGIA"
"ETATS UNIS D'AMERIQUE"

Breaker
"THE UNIVERSITY WAS FOUNDED IN 1867. IT HAS INSTRUCTED 6000 NEGRO STUDENTS"
"L'UNIVERSITÉ A ÉTÉ FONDÉE EN 1867. LA DONNÉ l'INSTRUCTION A'6000 ÉTUDIANTS NÈGRES"
"IT HAS GRADUATED 330 NEGROES AMONG WHOM ARE:"
"ELLE A D'ÉLIVRE DES DIPLOMES A 330 NÈGRES DONT :"

Bottom 
THE UNIVERSITY HAS 20 PROFESSORS AND INSTRUTORS AND 250 STUDENTS AT PRESENT.
     IT HAS FIVE BUILDING, 60 ACRES OF CAMPUS AND A LIBRARY OF 11,000 VOLUMES. IT AIMS TO RAISE
AND CIVILIZE THE SONS OF THE FREEDMEN BY TRAINING THEIR MORE CAPABLE MEMBERS IN THE LIBER-
AL ARTS ACCORDING TO THE BEST STANDARDS OF THE DAY.
     THE PROPER ACCOMPLISHMENT OF THIS WORK DEMANDS AN ENDOWMENT FUND OF $500,000.

Bottom french
L'UNIVERSITÉ A ACTUELLEMENT 20 PROFESSEURS ET INSTRUCTEURS ET 250 ÉTUDIANTS
     ELLE EST COMPOSEE DE CINC BÂTIMENTS, 60 ACRES (ENVIRON 26 HECTARES) DE TERRAIN SERVANT DE
COUR ET DE CHAMP DE RÉCREATION, ET D'UNE BIBLIOTHÈQUE CONTENANT 11,000 VOLUMES.
     SON BUT EST D'ÉLEVER ET DE CIVILISER LES FILS DES NEGRES AFFRANCHS EN DONNANT AUX MEUX
DOUES UNE ÉDUCATION DANS LES ARTS LIBÉRAUX EN ACCORD AVEC LES IDÉES LES PLUS PROGRESS -
SISTES DE L'EPOQUE.
     L'ACCOMPLISSEMENT DE CETTE OEUVRE  DEMANDE UNE DOTATION DE $500,000 (2,500,000 FRANCS) 

 -->

<script>
	import Pie from './Pie.svelte';
	import Map from './Map.svelte';
</script>

<h2 class="headline">
	<span>A series of statistical charts</span><br />
</h2>

<Map />
<!-- <Pie /> -->
